### ISSUE TITLE
Почему не загрузите в магазин дополнений?

### ISSUE THREAD

**Issue by ishpagin** [yoksel/htmla-project-checker#2]
Есть аккаунт разработчика, могу помочь с загрузкой в магазины chrome и mozilla для удобства пользователей

Например сейчас невозможно установить дополнение в firefox без знания консольной web-ext

**Comment by yoksel** [comment]
Честно говоря, я не знаю как сейчас выглядит страница проверки проектов. Возможно, уже можно обойтись и без расширения
